apiVersion: kafka.strimzi.io/v1alpha1
kind: Kafka
metadata:
  name: kafka-2
spec:
  kafka:
    version: 2.1.0
    replicas: 3
    listeners:
      plain: {}
      tls: {}
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.1"
      delete.topic.enable: "true"
    storage:
      type: persistent-claim
      size: 5Gi
      deleteClaim: true
      class: openebs-jiva-default
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 2Gi
      deleteClaim: true
      class: openebs-jiva-default
  entityOperator:
    topicOperator: {}
    userOperator: {}
---
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: Animals
  labels:
    strimzi.io/cluster: kafka-2
spec:
  partitions: 3
  replicas: 3
---
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaConnect
metadata:
  name: kafka-connect-2
spec:
  image: imranpochi/strmzi-kafka-connect-with-s3-plugin
  version: 2.2.0
  replicas: 1
  bootstrapServers: kafka-2-kafka-bootstrap:9092
  externalConfiguration:
    env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: aws-creds
            key: awsAccessKey
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: aws-creds
            key: awsSecretAccessKey